
package view;

import controller.ProdutoController;
import controller.VendaController;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.pojo.ItemCompra;
import model.pojo.ItemVenda;
import model.pojo.Produto;

/**
 *
 * @author Anderson
 */
public class ViewVenda extends javax.swing.JDialog {

    private Produto produto;
    private List<ItemVenda> itensVenda = new ArrayList<ItemVenda>();
    
    public ViewVenda(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.inicializaCampos();
    }
    
    private void inicializaCampos(){
        this.txtCliente.setText("");
        this.dtDataVenda.setDate(new Date());
        this.txtValorTotal.setText("0.00");        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JTabbedPane();
        pnlDadosVenda = new javax.swing.JPanel();
        pnlFormulario = new javax.swing.JPanel();
        lblCliente = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        btnBuscaCliente = new javax.swing.JButton();
        lblDataVenda = new javax.swing.JLabel();
        lblValorTotal = new javax.swing.JLabel();
        lblRS = new javax.swing.JLabel();
        txtValorTotal = new javax.swing.JTextField();
        dtDataVenda = new com.toedter.calendar.JDateChooser();
        pnlBotoes = new javax.swing.JPanel();
        btnFinalizarCompra = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        pnlItensVenda = new javax.swing.JPanel();
        pnlFormularioItens = new javax.swing.JPanel();
        lblProduto = new javax.swing.JLabel();
        txtProduto = new javax.swing.JTextField();
        btnBuscaProduto = new javax.swing.JButton();
        lblQuantidade = new javax.swing.JLabel();
        spQuantidade = new javax.swing.JSpinner();
        lblPreco = new javax.swing.JLabel();
        txtPreco = new javax.swing.JTextField();
        lblRSPreco = new javax.swing.JLabel();
        btnAdicionarItem = new javax.swing.JButton();
        btnRemoverItem = new javax.swing.JButton();
        scpItensVenda = new javax.swing.JScrollPane();
        tblItensVenda = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Venda");

        pnlFormulario.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Formulário"));

        lblCliente.setText("Cliente");

        txtCliente.setEditable(false);

        btnBuscaCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        btnBuscaCliente.setToolTipText("Selecione um fornecedor");
        btnBuscaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaClienteActionPerformed(evt);
            }
        });

        lblDataVenda.setText("Data da Compra");

        lblValorTotal.setText("Valor Total");

        lblRS.setText("R$");

        txtValorTotal.setEditable(false);

        javax.swing.GroupLayout pnlFormularioLayout = new javax.swing.GroupLayout(pnlFormulario);
        pnlFormulario.setLayout(pnlFormularioLayout);
        pnlFormularioLayout.setHorizontalGroup(
            pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFormularioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFormularioLayout.createSequentialGroup()
                        .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscaCliente))
                    .addComponent(lblCliente)
                    .addComponent(lblDataVenda)
                    .addComponent(lblValorTotal)
                    .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(dtDataVenda, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlFormularioLayout.createSequentialGroup()
                            .addComponent(lblRS)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 19, Short.MAX_VALUE))
        );
        pnlFormularioLayout.setVerticalGroup(
            pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFormularioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscaCliente))
                .addGap(11, 11, 11)
                .addComponent(lblDataVenda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dtDataVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblValorTotal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRS)
                    .addComponent(txtValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pnlBotoes.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnFinalizarCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        btnFinalizarCompra.setText("Finalizar Venda");
        btnFinalizarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarCompraActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBotoesLayout = new javax.swing.GroupLayout(pnlBotoes);
        pnlBotoes.setLayout(pnlBotoesLayout);
        pnlBotoesLayout.setHorizontalGroup(
            pnlBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnFinalizarCompra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlBotoesLayout.setVerticalGroup(
            pnlBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFinalizarCompra, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlDadosVendaLayout = new javax.swing.GroupLayout(pnlDadosVenda);
        pnlDadosVenda.setLayout(pnlDadosVendaLayout);
        pnlDadosVendaLayout.setHorizontalGroup(
            pnlDadosVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDadosVendaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDadosVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlFormulario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlDadosVendaLayout.setVerticalGroup(
            pnlDadosVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDadosVendaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlFormulario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnlPrincipal.addTab("Dados da Venda", pnlDadosVenda);

        pnlFormularioItens.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Formulário"));

        lblProduto.setText("Produto");

        txtProduto.setEditable(false);

        btnBuscaProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        btnBuscaProduto.setToolTipText("Selecione um produto");
        btnBuscaProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaProdutoActionPerformed(evt);
            }
        });

        lblQuantidade.setText("Quantidade");

        spQuantidade.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        lblPreco.setText("Preço");

        txtPreco.setEditable(false);

        lblRSPreco.setText("R$");

        btnAdicionarItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/plus.png"))); // NOI18N
        btnAdicionarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarItemActionPerformed(evt);
            }
        });

        btnRemoverItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/minus.png"))); // NOI18N
        btnRemoverItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverItemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlFormularioItensLayout = new javax.swing.GroupLayout(pnlFormularioItens);
        pnlFormularioItens.setLayout(pnlFormularioItensLayout);
        pnlFormularioItensLayout.setHorizontalGroup(
            pnlFormularioItensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFormularioItensLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFormularioItensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFormularioItensLayout.createSequentialGroup()
                        .addGroup(pnlFormularioItensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblQuantidade))
                        .addGap(12, 12, 12)
                        .addComponent(lblRSPreco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlFormularioItensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlFormularioItensLayout.createSequentialGroup()
                                .addComponent(lblPreco)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(pnlFormularioItensLayout.createSequentialGroup()
                                .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAdicionarItem, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnRemoverItem, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlFormularioItensLayout.createSequentialGroup()
                        .addGroup(pnlFormularioItensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblProduto)
                            .addGroup(pnlFormularioItensLayout.createSequentialGroup()
                                .addComponent(txtProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscaProduto)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlFormularioItensLayout.setVerticalGroup(
            pnlFormularioItensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFormularioItensLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFormularioItensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnBuscaProduto)
                    .addGroup(pnlFormularioItensLayout.createSequentialGroup()
                        .addComponent(lblProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlFormularioItensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuantidade)
                    .addComponent(lblPreco))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFormularioItensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFormularioItensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(spQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblRSPreco)
                        .addComponent(btnAdicionarItem))
                    .addComponent(btnRemoverItem))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblItensVenda.setAutoCreateRowSorter(true);
        tblItensVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Quantidade", "Preço Unitário"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scpItensVenda.setViewportView(tblItensVenda);

        javax.swing.GroupLayout pnlItensVendaLayout = new javax.swing.GroupLayout(pnlItensVenda);
        pnlItensVenda.setLayout(pnlItensVendaLayout);
        pnlItensVendaLayout.setHorizontalGroup(
            pnlItensVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlItensVendaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlItensVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scpItensVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(pnlFormularioItens, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlItensVendaLayout.setVerticalGroup(
            pnlItensVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlItensVendaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlFormularioItens, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scpItensVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlPrincipal.addTab("Itens da Venda", pnlItensVenda);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnBuscaProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaProdutoActionPerformed
        ViewBuscaProdutos vbProdutos = new ViewBuscaProdutos(null, true);
        vbProdutos.setLocationRelativeTo(this);
        vbProdutos.setVisible(true);
        String nomeProduto = vbProdutos.getNomeProduto();
        if(nomeProduto!=null){
            produto = ProdutoController.getInstance().readProdutoByNome(nomeProduto);
            txtProduto.setText(produto.getNome());
            txtPreco.setText(String.valueOf(produto.getPrecoVenda()));
        }
    }//GEN-LAST:event_btnBuscaProdutoActionPerformed

    private void btnBuscaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaClienteActionPerformed
      
        ViewBuscaClientes vbClientes = new ViewBuscaClientes(null, true);
        vbClientes.setLocationRelativeTo(this);
        vbClientes.setVisible(true);
        String nomeCliente = vbClientes.getNomeCliente();
        if(nomeCliente!=null){
            txtCliente.setText(nomeCliente);
        }
        
    }//GEN-LAST:event_btnBuscaClienteActionPerformed

    private void btnAdicionarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarItemActionPerformed
        if(txtProduto.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Nenhum produto selecionado!");
        }else{
            this.adicionaItemVenda();
        }
    }//GEN-LAST:event_btnAdicionarItemActionPerformed

    private void btnRemoverItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverItemActionPerformed
        this.removeItemVenda();
    }//GEN-LAST:event_btnRemoverItemActionPerformed

    private void btnFinalizarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarCompraActionPerformed
        
        if(txtCliente.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Nenhum cliente selecionado!");
        }else{
            if(itensVenda.isEmpty()){
                JOptionPane.showMessageDialog(this, "Não existem itens adicionados!");
            }else{
                int opcao = JOptionPane.showConfirmDialog(this, "Deseja finalizar venda?");
                
                if(opcao==JOptionPane.YES_OPTION){
                    this.finalizaVenda();
                }
            }
        } 
    }//GEN-LAST:event_btnFinalizarCompraActionPerformed

    private void finalizaVenda(){
        boolean resultado;
        resultado = VendaController.getInstance().createVenda(txtCliente.getText(), dtDataVenda.getDate(),
                Double.parseDouble(txtValorTotal.getText()),itensVenda);
    
        if(resultado==false){
            JOptionPane.showMessageDialog(this, "Venda finalizada com sucesso!");
            
            //Limpar todos os campos da compra
            txtCliente.setText("");
            txtProduto.setText("");
            txtValorTotal.setText("0");
            dtDataVenda.setDate(new Date());
            spQuantidade.setValue(1);
            itensVenda.clear();
            this.atualizaItensVenda();
        }else{
            JOptionPane.showMessageDialog(this, "Falha ao salvar a venda!");
        }
    }
    
    private void removeItemVenda(){
        DefaultTableModel modeloTabela = (DefaultTableModel) tblItensVenda.getModel();
        
        if(modeloTabela.getRowCount()<=0){
            JOptionPane.showMessageDialog(this, "Não existem itens para remoção!");
        }else{
            if(tblItensVenda.getSelectedRow()<0){
                JOptionPane.showMessageDialog(this, "Nenhum item selecionado!");
            }else{
                Long id = (Long) tblItensVenda.getValueAt(tblItensVenda.getSelectedRow(),0);
                Integer qtde = (int) tblItensVenda.getValueAt(tblItensVenda.getSelectedRow(),2);
                Double preco = (Double) tblItensVenda.getValueAt(tblItensVenda.getSelectedRow(),3);
                
                List<ItemVenda> copiaItens = new ArrayList<ItemVenda>();
                
                copiaItens.addAll(itensVenda);
                
                for(ItemVenda iv: copiaItens){
                    if(iv.getProduto().getId().intValue()==id.intValue()
                    && iv.getQuantidade().intValue()==qtde){
                        itensVenda.remove(iv);
                        break;
                    }
                }
                
                double totalVenda = Double.parseDouble(txtValorTotal.getText());
                
                totalVenda = totalVenda - qtde * preco;
                
                txtValorTotal.setText(String.valueOf(totalVenda));
                
                this.atualizaItensVenda();
                
                
            }   
        }
    }
    
    private void adicionaItemVenda(){
        int qtde = (int) spQuantidade.getValue();
        
        if(produto.getQuantidadeEstoque().intValue()<qtde){
            JOptionPane.showMessageDialog(this,"Quantidade não disponível!\n\n"
                    + "Quantidade disponível: " + produto.getQuantidadeEstoque());
        }else{
            ItemVenda item = new ItemVenda();
            item.setProduto(produto);
            item.setQuantidade(qtde);
            item.setValorUnitario(produto.getPrecoVenda());
            itensVenda.add(item);
            this.atualizaItensVenda();
            double totalVenda = Double.parseDouble(txtValorTotal.getText());
            totalVenda = totalVenda + qtde * produto.getPrecoVenda();
            txtValorTotal.setText(String.valueOf(totalVenda));            
            this.limparCamposProduto();
        }
        
    }
    
    private void limparCamposProduto(){
        txtProduto.setText("");
        txtPreco.setText("");
        spQuantidade.setValue(1);
    }
    
    private void atualizaItensVenda(){
        DefaultTableModel modeloTabela = (DefaultTableModel) tblItensVenda.getModel();
        //Limpa tabela        
        while(modeloTabela.getRowCount()>0){
            modeloTabela.removeRow(0);
        }
        //Preenche os dados na tabela
        for(ItemVenda iv: itensVenda){
            Object[] row = {
                iv.getProduto().getId(),
                iv.getProduto().getNome(),
                iv.getQuantidade(),
                iv.getProduto().getPrecoVenda()
            };
            modeloTabela.addRow(row);
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarItem;
    private javax.swing.JButton btnBuscaCliente;
    private javax.swing.JButton btnBuscaProduto;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnFinalizarCompra;
    private javax.swing.JButton btnRemoverItem;
    private com.toedter.calendar.JDateChooser dtDataVenda;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblDataVenda;
    private javax.swing.JLabel lblPreco;
    private javax.swing.JLabel lblProduto;
    private javax.swing.JLabel lblQuantidade;
    private javax.swing.JLabel lblRS;
    private javax.swing.JLabel lblRSPreco;
    private javax.swing.JLabel lblValorTotal;
    private javax.swing.JPanel pnlBotoes;
    private javax.swing.JPanel pnlDadosVenda;
    private javax.swing.JPanel pnlFormulario;
    private javax.swing.JPanel pnlFormularioItens;
    private javax.swing.JPanel pnlItensVenda;
    private javax.swing.JTabbedPane pnlPrincipal;
    private javax.swing.JScrollPane scpItensVenda;
    private javax.swing.JSpinner spQuantidade;
    private javax.swing.JTable tblItensVenda;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtPreco;
    private javax.swing.JTextField txtProduto;
    private javax.swing.JTextField txtValorTotal;
    // End of variables declaration//GEN-END:variables
}
