/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.Connection;
import java.util.HashMap;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.GerenciadorConexao;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;


public class ViewPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form ViewPrincipal
     */
    public ViewPrincipal() {
        initComponents();
        
        ImageIcon icone = new ImageIcon(getClass().getResource("/images/icone.png"));
        this.setIconImage(icone.getImage());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        lblSiscom = new javax.swing.JLabel();
        tbrPrincipal = new javax.swing.JToolBar();
        btnCliente = new javax.swing.JButton();
        btnFornecedor = new javax.swing.JButton();
        btnProduto = new javax.swing.JButton();
        btnCompra = new javax.swing.JButton();
        bntVenda = new javax.swing.JButton();
        mnbPrincipal = new javax.swing.JMenuBar();
        mnArquivo = new javax.swing.JMenu();
        mniNovoFornecedor = new javax.swing.JMenuItem();
        mniNovoCliente = new javax.swing.JMenuItem();
        mniNovoProduto = new javax.swing.JMenuItem();
        mniNovaCompra = new javax.swing.JMenuItem();
        mniNovaVenda = new javax.swing.JMenuItem();
        mniSair = new javax.swing.JMenuItem();
        mnRelatorio = new javax.swing.JMenu();
        mniFornecedoresCadastrados = new javax.swing.JMenuItem();
        mniClientesCadastrados = new javax.swing.JMenuItem();
        mniProdutosCadastrados = new javax.swing.JMenuItem();
        mniVendasPeriodo = new javax.swing.JMenuItem();
        mnAjuda = new javax.swing.JMenu();
        mniSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SisCom");

        pnlPrincipal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblSiscom.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblSiscom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSiscom.setText("SISCOM");
        lblSiscom.setToolTipText("");

        tbrPrincipal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tbrPrincipal.setFloatable(false);
        tbrPrincipal.setRollover(true);

        btnCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cliente.png"))); // NOI18N
        btnCliente.setText("Cliente");
        btnCliente.setFocusable(false);
        btnCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCliente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteActionPerformed(evt);
            }
        });
        tbrPrincipal.add(btnCliente);

        btnFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fornecedor.png"))); // NOI18N
        btnFornecedor.setText("Fornecedor");
        btnFornecedor.setFocusable(false);
        btnFornecedor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFornecedor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFornecedorActionPerformed(evt);
            }
        });
        tbrPrincipal.add(btnFornecedor);

        btnProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/produto.png"))); // NOI18N
        btnProduto.setText("Produto");
        btnProduto.setFocusable(false);
        btnProduto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnProduto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdutoActionPerformed(evt);
            }
        });
        tbrPrincipal.add(btnProduto);

        btnCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/compra.png"))); // NOI18N
        btnCompra.setText("Compra");
        btnCompra.setFocusable(false);
        btnCompra.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCompra.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompraActionPerformed(evt);
            }
        });
        tbrPrincipal.add(btnCompra);

        bntVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/venda.png"))); // NOI18N
        bntVenda.setText("Venda");
        bntVenda.setFocusable(false);
        bntVenda.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bntVenda.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bntVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntVendaActionPerformed(evt);
            }
        });
        tbrPrincipal.add(bntVenda);

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSiscom, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
            .addComponent(tbrPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
                .addComponent(tbrPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSiscom, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE))
        );

        mnbPrincipal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        mnArquivo.setText("Arquivo");

        mniNovoFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cliente.png"))); // NOI18N
        mniNovoFornecedor.setText("Novo Fornecedor");
        mniNovoFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniNovoFornecedorActionPerformed(evt);
            }
        });
        mnArquivo.add(mniNovoFornecedor);

        mniNovoCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fornecedor.png"))); // NOI18N
        mniNovoCliente.setText("Novo Cliente");
        mniNovoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniNovoClienteActionPerformed(evt);
            }
        });
        mnArquivo.add(mniNovoCliente);

        mniNovoProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/produto.png"))); // NOI18N
        mniNovoProduto.setText("Novo Produto");
        mniNovoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniNovoProdutoActionPerformed(evt);
            }
        });
        mnArquivo.add(mniNovoProduto);

        mniNovaCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/compra.png"))); // NOI18N
        mniNovaCompra.setText("Nova Compra");
        mniNovaCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniNovaCompraActionPerformed(evt);
            }
        });
        mnArquivo.add(mniNovaCompra);

        mniNovaVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/venda.png"))); // NOI18N
        mniNovaVenda.setText("Nova Venda");
        mniNovaVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniNovaVendaActionPerformed(evt);
            }
        });
        mnArquivo.add(mniNovaVenda);

        mniSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        mniSair.setText("Sair");
        mniSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniSairActionPerformed(evt);
            }
        });
        mnArquivo.add(mniSair);

        mnbPrincipal.add(mnArquivo);

        mnRelatorio.setText("Relatórios");

        mniFornecedoresCadastrados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fornecedores_cadastrados.png"))); // NOI18N
        mniFornecedoresCadastrados.setText("Fornecedores Cadastrados");
        mniFornecedoresCadastrados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniFornecedoresCadastradosActionPerformed(evt);
            }
        });
        mnRelatorio.add(mniFornecedoresCadastrados);

        mniClientesCadastrados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clientes_cadastrados.png"))); // NOI18N
        mniClientesCadastrados.setText("Clientes Cadastrados");
        mniClientesCadastrados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniClientesCadastradosActionPerformed(evt);
            }
        });
        mnRelatorio.add(mniClientesCadastrados);

        mniProdutosCadastrados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/produto.png"))); // NOI18N
        mniProdutosCadastrados.setText("Produtos Cadastrados");
        mniProdutosCadastrados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniProdutosCadastradosActionPerformed(evt);
            }
        });
        mnRelatorio.add(mniProdutosCadastrados);

        mniVendasPeriodo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/filtro.png"))); // NOI18N
        mniVendasPeriodo.setText("Vendas por Período");
        mniVendasPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniVendasPeriodoActionPerformed(evt);
            }
        });
        mnRelatorio.add(mniVendasPeriodo);

        mnbPrincipal.add(mnRelatorio);

        mnAjuda.setText("Ajuda");

        mniSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/info.jpg"))); // NOI18N
        mniSobre.setText("Sobre");
        mniSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniSobreActionPerformed(evt);
            }
        });
        mnAjuda.add(mniSobre);

        mnbPrincipal.add(mnAjuda);

        setJMenuBar(mnbPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniSairActionPerformed
        int opcao;
        opcao = JOptionPane.showConfirmDialog(this, "Deseja realmente sair?");
        if(opcao==JOptionPane.YES_OPTION){
            System.exit(opcao);
        }
    }//GEN-LAST:event_mniSairActionPerformed

    private void mniNovoFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniNovoFornecedorActionPerformed
        ViewCadastroFornecedor vcFornecedor = new ViewCadastroFornecedor(this, true);
        vcFornecedor.setLocationRelativeTo(this);
        vcFornecedor.setVisible(true);
    }//GEN-LAST:event_mniNovoFornecedorActionPerformed

    private void mniSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniSobreActionPerformed
        ViewSobre vSobre = new ViewSobre(this, true);
        vSobre.setLocationRelativeTo(this);
        vSobre.setVisible(true);
    }//GEN-LAST:event_mniSobreActionPerformed

    private void mniNovoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniNovoClienteActionPerformed
        ViewCadastroCliente vcCliente = new ViewCadastroCliente(this, true);
        vcCliente.setLocationRelativeTo(this);
        vcCliente.setVisible(true);
    }//GEN-LAST:event_mniNovoClienteActionPerformed

    private void mniFornecedoresCadastradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniFornecedoresCadastradosActionPerformed
        
        JasperPrint relatorio;
        
        try {
            Connection conn  = GerenciadorConexao.getInstance().getConexao();
            HashMap map = new HashMap();
            String arquivoJasper = "src/relatorios/fornecedores_cadastrados.jasper";
            
            relatorio = JasperFillManager.fillReport(arquivoJasper,map,conn);
            
            JasperViewer jv = new JasperViewer(relatorio,false);
            jv.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            jv.setExtendedState(JFrame.MAXIMIZED_BOTH);
            jv.setIconImage(this.getIconImage());
            jv.setTitle("Fornecedores Cadastrados");
            jv.setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Falha ao gerar o relatório de fornecedores");
        }    
        
        
    }//GEN-LAST:event_mniFornecedoresCadastradosActionPerformed

    private void mniClientesCadastradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniClientesCadastradosActionPerformed
        
        JasperPrint relatorio;        
        try {
            Connection conn  = GerenciadorConexao.getInstance().getConexao();
            HashMap map = new HashMap();
            String arquivoJasper = "src/relatorios/clientes_cadastrados.jasper";
            
            relatorio = JasperFillManager.fillReport(arquivoJasper,map,conn);
            
            JasperViewer jv = new JasperViewer(relatorio,false);
            jv.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            jv.setExtendedState(JFrame.MAXIMIZED_BOTH);
            jv.setIconImage(this.getIconImage());
            jv.setTitle("Clientes Cadastrados");
            jv.setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Falha ao gerar o relatório de clientes");
        }            
    }//GEN-LAST:event_mniClientesCadastradosActionPerformed

    private void btnFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFornecedorActionPerformed
        ViewRelatorioFornecedores vrFornecedores = new ViewRelatorioFornecedores(this, true);
        vrFornecedores.setLocationRelativeTo(this);
        vrFornecedores.setVisible(true);
    }//GEN-LAST:event_btnFornecedorActionPerformed

    private void btnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteActionPerformed
        ViewRelatorioClientes vrClientes = new ViewRelatorioClientes(this, true);
        vrClientes.setLocationRelativeTo(this);
        vrClientes.setVisible(true);
    }//GEN-LAST:event_btnClienteActionPerformed

    private void mniNovoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniNovoProdutoActionPerformed
        ViewCadastroProduto vcProduto = new ViewCadastroProduto(this, true);
        vcProduto.setLocationRelativeTo(this);
        vcProduto.setVisible(true);
    }//GEN-LAST:event_mniNovoProdutoActionPerformed

    private void btnProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdutoActionPerformed
        ViewRelatorioProdutos vrProdutos = new ViewRelatorioProdutos(this, true);
        vrProdutos.setLocationRelativeTo(this);
        vrProdutos.setVisible(true);
    }//GEN-LAST:event_btnProdutoActionPerformed

    private void mniProdutosCadastradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniProdutosCadastradosActionPerformed
        JasperPrint relatorio;        
        try {
            Connection conn  = GerenciadorConexao.getInstance().getConexao();
            HashMap map = new HashMap();
            String arquivoJasper = "src/relatorios/produtos_cadastrados.jasper";
            
            
            
            relatorio = JasperFillManager.fillReport(arquivoJasper,map,conn);
            
            JasperViewer jv = new JasperViewer(relatorio,false);
            jv.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            jv.setExtendedState(JFrame.MAXIMIZED_BOTH);
            jv.setIconImage(this.getIconImage());
            jv.setTitle("Produtos Cadastrados");
            jv.setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Falha ao gerar o relatório de clientes");
        }            
        
    }//GEN-LAST:event_mniProdutosCadastradosActionPerformed

    private void mniNovaCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniNovaCompraActionPerformed
        ViewCompra vCompra = new ViewCompra(this, true);
        vCompra.setLocationRelativeTo(this);
        vCompra.setVisible(true);
        
    }//GEN-LAST:event_mniNovaCompraActionPerformed

    private void btnCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompraActionPerformed
        this.mniNovaCompraActionPerformed(evt);
    }//GEN-LAST:event_btnCompraActionPerformed

    private void mniNovaVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniNovaVendaActionPerformed
        ViewVenda vVenda = new ViewVenda(this, true);
        vVenda.setLocationRelativeTo(this);
        vVenda.setVisible(true);
    }//GEN-LAST:event_mniNovaVendaActionPerformed

    private void bntVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntVendaActionPerformed
        this.mniNovaVendaActionPerformed(evt);
    }//GEN-LAST:event_bntVendaActionPerformed

    private void mniVendasPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniVendasPeriodoActionPerformed
        VendasPeriodo vendasDialog = new VendasPeriodo(this, true);
        vendasDialog.setLocationRelativeTo(this);
        vendasDialog.setVisible(true);
    }//GEN-LAST:event_mniVendasPeriodoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntVenda;
    private javax.swing.JButton btnCliente;
    private javax.swing.JButton btnCompra;
    private javax.swing.JButton btnFornecedor;
    private javax.swing.JButton btnProduto;
    private javax.swing.JLabel lblSiscom;
    private javax.swing.JMenu mnAjuda;
    private javax.swing.JMenu mnArquivo;
    private javax.swing.JMenu mnRelatorio;
    private javax.swing.JMenuBar mnbPrincipal;
    private javax.swing.JMenuItem mniClientesCadastrados;
    private javax.swing.JMenuItem mniFornecedoresCadastrados;
    private javax.swing.JMenuItem mniNovaCompra;
    private javax.swing.JMenuItem mniNovaVenda;
    private javax.swing.JMenuItem mniNovoCliente;
    private javax.swing.JMenuItem mniNovoFornecedor;
    private javax.swing.JMenuItem mniNovoProduto;
    private javax.swing.JMenuItem mniProdutosCadastrados;
    private javax.swing.JMenuItem mniSair;
    private javax.swing.JMenuItem mniSobre;
    private javax.swing.JMenuItem mniVendasPeriodo;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JToolBar tbrPrincipal;
    // End of variables declaration//GEN-END:variables
}
